name: 🌉 Puente Revivir

on:
  # Señal directa desde la web (sin exponer secretos en el front)
  repository_dispatch:
    types: [revivir_web]

  # Alternativa ya probada: tocar trigger/revivir.txt
  push:
    paths:
      - 'trigger/revivir.txt'

permissions:
  actions: write
  contents: read

jobs:
  dispatch_activar_revivir:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Disparar activar-revivir.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Invocando workflow activar-revivir.yml en rama main…"
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/activar-revivir.yml/dispatches" \
            -d '{"ref":"main"}'
          echo "✅ Señal enviada"
