name: 🌉 Puente Revivir
on:
  push:
    paths:
      - 'trigger/revivir.txt'

jobs:
  bridge:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: 🚀 Disparar activar-revivir.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/activar-revivir.yml/dispatches \
            -d '{"ref":"main"}'
          echo "OK"
